version: '3.8'

services:
  toolbox:
    image: repo.nicely.gg/toolbox
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.toolbox.rule=Host(`toolbox.nicely.gg`)
      - traefik.http.routers.toolbox.tls=true
      - traefik.http.routers.toolbox.tls.certresolver=le
      - traefik.http.services.toolbox.loadbalancer.server.port=3000
    environment:
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=3000
      - MONGODB_URL=mongodb://mongodb
    networks:
      - toolbox
      - traefik

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    networks:
      - toolbox

networks:
  toolbox:
  traefik:
    external: true
